Repository divi-24/SheSync, pull requests merged in 2025-08, with the labels that each got.

#402 blog page created
  package-lock.json
  package.json
  src/components/Blog.jsx
  src/components/Education.jsx
  src/components/Landing.jsx
  src/components/SideBar.jsx
  src/routes/appRoutes.jsx
Labels: SSoC25, Intermediate

#420 Improve the health management section
  src/components/AboutUs.jsx
  styles/style.css
Labels: SSoC25, Beginner

#427 Improve the mission section
  src/components/AboutUs.jsx
Labels: SSoC25, Beginner

#432 Removed-contributor-page
  src/components/SideBar.jsx
  src/routes/appRoutes.jsx
Labels: level 3, gssoc 25

#444 Enhance the key section
  src/components/AboutUs.jsx
Labels: SSoC25, Beginner
