Repository divi-24/SheSync, pull requests merged in 2025-07, with the labels that each got.

#293 Resolved Issue #265: Corrected the Active links issue in sidebar
  src/components/Forum.jsx
  src/components/ParentDashboard.jsx
  src/components/SymptomAnalysis.jsx
Labels: SSoC25, Beginner

#302 improve the CSS of Profile Section Options in Community
  .env.example
  src/components/Forum.jsx
Labels: level 1, gssoc 25

#304 Fix footer link light theme
  src/components/Landing.jsx
Labels: SSoC25, Beginner

#310 Updated auth logic and UI for contributors page
  src/components/Contributors.jsx
  src/routes/appRoutes.jsx
Labels: SSoC25, Beginner

#319 🎮 feature: add health-themed Hangman game with pregnancy and menstrual c…
  public/bliss/images/Hangman.png
  src/components/Bliss/Bliss.jsx
  src/components/Bliss/games/Hangman.jsx
  src/routes/appRoutes.jsx
Labels: level 2, gssoc 25

#332 Fixed Consultation Page
  src/components/Dashboard.jsx
  src/components/Ecom.jsx
Labels: SSoC25, Beginner

#340 Fix: icon hover state on two product cards
  public/images/products/Bath.png
  public/images/products/Hand_Heart.png
  src/components/Ecom.jsx
Labels: SSoC25, Beginner

#346 improvise and implement consistent dark mode in contributors page
  src/components/Contributors.jsx
Labels: SSoC25, Beginner
